#!/bin/bash

# JankyBorders configuration
# https://github.com/FelixKratz/JankyBorders

# Catppuccin Mocha colors
# Pink: #f5c2e7
# Surface0: #313244

borders active_color=0xfff5c2e7 inactive_color=0x00000000 width=6.0 &
